version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "terragon-labs"
    assignees:
      - "terragon-labs"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    groups:
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "isort"
          - "mypy"
          - "flake8*"
          - "pylint"
          - "bandit"
          - "safety"
          - "pre-commit"
        update-types:
          - "minor"
          - "patch"
      security-dependencies:
        patterns:
          - "cryptography"
          - "requests"
          - "urllib3"
        update-types:
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "black"
          - "isort" 
          - "mypy"
          - "flake8*"
          - "pylint"
          - "bandit"
          - "safety"
          - "pre-commit"
        update-types:
          - "minor"
          - "patch"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "terragon-labs"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    reviewers:
      - "terragon-labs"
    labels:
      - "dependencies"
      - "github-actions"