blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Report
    url: https://github.com/danieleschmidt/claude-manager-service/security/advisories/new
    about: Please report security vulnerabilities through GitHub Security Advisories
  - name: General Discussion
    url: https://github.com/danieleschmidt/claude-manager-service/discussions
    about: Ask questions and discuss ideas with the community