name: 1. Scan Repos and Propose Tasks

on:
  schedule:
    - cron: '0 5 * * *' # Run daily at 5 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write # Required to create issues
    steps:
      - name: Checkout Manager Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scanner and Create Task Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: python src/task_analyzer.py
